plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton

title: Dexter
description: Just a blog
author: Dexter
email: dexter7isme@gmail.com
avatar: /logo.jpeg


google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
